variable "ssh_key_path" {
  type        = string
  description = "Save location for ssh public keys generated by the module"
}

variable "generate_ssh_key" {
  type        = bool
  description = "Whether or not to generate an SSH key"
}

variable "public_subnet_ids" {
  type        = list(string)
  description = "IDs of the created public subnets"
}

variable "vpc_id" {
  type        = string
  description = "The Id of the VPC to run RDS in."
}

variable "vpc_sg" {
  type        = string
  description = "The Id of the VPC security group to associate with the jump host."
}
