[GLOBAL]
pants_version = "2.14.0"
build_ignore = [
  "3rdparty/python/*",
  "docs/*"
]
backend_packages.add = [
  "pants.backend.awslambda.python",
  "pants.backend.experimental.terraform",
  "pants.backend.build_files.fmt.buildifier",
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.docker",
  "pants.backend.shell",
  "pants.backend.shell.lint.shfmt",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  '/src/python',
  '/test/python',
]

[python]
interpreter_constraints = [">=3.9"]
enable_resolves = true
resolves = { python-default = "3rdparty/python/requirements_lock.txt"}

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]

[terraform-validate]
skip = true

[docker]
default_repository = "{directory}"

[docker.registries.default-registry]
address = "%(env.BEEFLOW_AWS_ACCOUNT_ID)s.dkr.ecr.%(env.BEEFLOW_AWS_REGION)s.amazonaws.com"
default = true
