[GLOBAL]
pants_version = "2.14.0"
build_ignore = [
  "3rdparty/python/*",
  "docs/*"
]
backend_packages.add = [
  "pants.backend.awslambda.python",
  "pants.backend.experimental.terraform",
  "pants.backend.build_files.fmt.buildifier",
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.docker",
  "pants.backend.shell",
  "pants.backend.shell.lint.shfmt",
]
build_file_prelude_globs = ["pants-plugins/macros.py"]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  '/src/python',
  '/test/python',
  '/notebooks',
  '/pants-plugins',
]

[python]
interpreter_constraints = [">=3.9"]
enable_resolves = true

[python.resolves]
python-default = "3rdparty/python/requirements_lock.txt"
python-jupyter = "3rdparty/python/jupyter_lab.txt"

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]

[terraform-validate]
skip = true

[docker]
default_repository = "{directory}"

[docker.registries.default-registry]
address = "%(env.BEEFLOW_AWS_ACCOUNT_ID)s.dkr.ecr.%(env.BEEFLOW_AWS_REGION)s.amazonaws.com"
default = true

[test]
extra_env_vars = ["BEEFLOW__SKIP_CONFIG_PULL=1", "AWS_DEFAULT_REGION=us-east-2"]
