[GLOBAL]
pants_version = "2.11.0"
build_ignore = [
  "3rdparty/python/*",
  "docs/*"
]
backend_packages.add = [
  "pants.backend.awslambda.python",
  "pants.backend.experimental.terraform",
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.docker"
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  '/src/python',
  '/test/python',
]

[python]
interpreter_constraints = [">=3.9"]
enable_resolves = true
resolves = { python-default = "3rdparty/python/requirements_lock.txt"}
lockfile_generator = "pex"

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]

[terraform-validate]
skip = true

[docker]
default_repository = "{directory}"

[docker.registries.company-registry1]
address = "239132468951.dkr.ecr.us-east-2.amazonaws.com"
default = true
