[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
skip_gitignore = true
known_beeflow = 'beeflow'
default_section = 'THIRDPARTY'
sections = ['FUTURE','STDLIB','THIRDPARTY','beeflow','FIRSTPARTY','LOCALFOLDER']

[tool.black]
line-length = 88
target-version = ['py39']
exclude = '''
(
  /(
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | \bazel-*
    | \bazel-bin
    | \bazel-genfiles
    | \bazel-out
    | \bazel-testlogs
  )/
)
'''

[tool.pyright]
exclude = [
    "bazel-*/",
]
