version: "3.8"

services:
  airflow_base:
    container_name: "airflow_main"
    image: apache/airflow:2.3.2-python3.8
    network_mode: host
    command: airflow

  # Run with: docker-compose run --rm airflow_local db upgrade
  airflow_local:
    extends:
      service: airflow_base
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://postgres:postgres@localhost:5432/postgres
