version: "3.8"

services:
  terragrunt_base:
    container_name: "terragrunt_main"
    build: .
    network_mode: host
    command: "bash -c"
    volumes:
      - ../..:/data
      - /data/dist/export

  terragrunt_aws:
    extends:
      service: terragrunt_base
    working_dir: /data/infrastructure/terragrunt/aws
    volumes:
      - $HOME/.aws/config:/root/.aws/config:ro
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    # NOTE: This is not concurrency safe (https://github.com/gruntwork-io/terragrunt/issues/561)
    environment:
      - TERRAGRUNT_DOWNLOAD=/data/.terragrunt-cache-aws
      - TF_PLUGIN_CACHE_DIR=/data/.plugins-aws
      - BEEFLOW_AWS_REGION=${BEEFLOW_AWS_REGION}
      - BEEFLOW_AWS_ACCOUNT_ID=${BEEFLOW_AWS_ACCOUNT_ID}
