jupyter_lab(
    name = "python-jupyter",
    requirements = [
        "boto3==1.26.8",
        "pandas==1.5.2",
        "plotly==5.11.0",
        "kaleido==0.2.1",
        "rich==13.3.2",
        "ipywidgets==8.0.5",
        "networkx==3.0.0",
        "matplotlib==3.7.1",
        "pygraphviz==1.10",
    ],
    skip_mypy = True,
)
